# Generated by Django 4.2.3 on 2023-08-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('Editorial', models.CharField(max_length=100)),
                ('año_publicacion', models.IntegerField()),
            ],
        ),
    ]
