# Generated by Django 4.2.4 on 2023-08-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_autores_usuarios_registrados_alter_libros_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios_registrados',
            new_name='Empleados',
        ),
    ]
